name: Skript-Groq
author: Kerkkoh
description: A skript to interface with the Groq API.
version: 1.0
main: org.kerkkoh.skriptgroq.SkriptGroq
depend: [Skript]
commands:
  skriptgroq:
    description: The commands from SkriptGroq.
